import {ChangeEvent, useState} from "react";
import authService from "../services/authentication/authService";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import WrongEmail from "../components/login/WrongEmail";
import CodeSent from "../components/login/CodeSent";

const SDivLoginPageWrapper = styled.div`
  .logo {
    transform: scale(2);
  }
`

const ForgotPassword = () => {
    const [userName, setUserName] = useState<string>('')
    const handleUserNameInputChange = (event: ChangeEvent<HTMLInputElement>) => {
        setUserName(event.target.value)
    }
    // 3. Click sign in > send data
    const handleCheckEmail = async () => {
        // Send data to server
        const data = await authService.forgotPassword(userName)

        if (data?.status?.code === 200) {
            showCodeSentAlert()
            setTimeout(()=>{
                navigateToChangePassword()
            }, 5000)
            //@ts-ignore
        } else if (data?.error === 400) {
            showWrongEmailAlert()
        }
    }

    const [showWrongEmail, setShowWrongEmail] = useState(false)
    const [showCodeSent, setShowCodeSent] = useState(false)

    const showWrongEmailAlert = () => {
        setShowWrongEmail(true)
        setTimeout(() => {
            setShowWrongEmail(false)
        }, 3000)
    }

    const showCodeSentAlert = () => {
        setShowCodeSent(true)
        setTimeout(() => {
            setShowCodeSent(false)
        }, 3000)
    }

    // 4. If success, navigate to the `patient` page
    const navigateToTheLoginPage = () => {
        location.assign('/login')
    }

    const navigateToChangePassword = () => {
        location.assign('/change-password')
    }

    const navigateToTheSignUpPage = () => {
        location.assign('/signup')
    }

    return (
        <SDivLoginPageWrapper className="gray-bg middle-box text-center loginscreen animated fadeInDown">
            <style dangerouslySetInnerHTML={{__html: `body{background: #f3f3f4}`}}/>
            <Head>
                <title>Change Password</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <meta charSet="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <link href="css/bootstrap.min.css" rel="stylesheet"/>
                <link href="font-awesome/css/font-awesome.css" rel="stylesheet"/>

                <link href="css/animate.css" rel="stylesheet"/>
                <link href="css/style.css" rel="stylesheet"/>
            </Head>

            <div>
                <div className="logo">
                    <Image width={500} height={250} src="/img/logo.png" alt="Phi Logo"/>
                </div>
                <h3>Welcome to PHI</h3>
                <p>Change new password</p>
                <div className="m-t">
                    <div className="form-group">
                        <input type="email" onChange={handleUserNameInputChange} value={userName}
                               className="form-control" placeholder="Your Email" required/>
                    </div>
                    <button onClick={handleCheckEmail} className="btn btn-primary block full-width m-b">Submit
                    </button>
                    {showCodeSent && <CodeSent/>}
                    {showWrongEmail && <WrongEmail/>}
                    <p>or</p>
                    <button onClick={navigateToTheSignUpPage} className="btn bg-light block full-width m-b">Register new
                        account
                    </button>
                </div>
            </div>
        </SDivLoginPageWrapper>
    )
}

export default ForgotPassword