import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <meta charSet="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <link href="css/bootstrap.min.css" rel="stylesheet"/>
                <link href="font-awesome/css/font-awesome.css" rel="stylesheet"/>

                <link href="css/animate.css" rel="stylesheet"/>
                <link href="css/style.css" rel="stylesheet"/>
            </Head>

            <main className={styles.main}>
                <div id="wrapper">

                    <nav className="navbar-default navbar-static-side" role="navigation">
                        <div className="sidebar-collapse">
                            <ul className="nav metismenu" id="side-menu">
                                <li className="nav-header">
                                    <div className="dropdown profile-element">
                                        <a data-toggle="dropdown" className="dropdown-toggle" href="#">
                                            <span className="block m-t-xs font-bold">Example user</span>
                                            <span className="text-muted text-xs block">menu <b
                                                className="caret"></b></span>
                                        </a>
                                        <ul className="dropdown-menu animated fadeInRight m-t-xs">
                                            <li><a className="dropdown-item" href="login.html">Logout</a></li>
                                        </ul>
                                    </div>
                                    <div className="logo-element">
                                        IN+
                                    </div>
                                </li>
                                <li className="active">
                                    <a href="index.html"><i className="fa fa-th-large"></i> <span className="nav-label">Main view</span></a>
                                </li>
                                <li>
                                    <a href="minor.html"><i className="fa fa-th-large"></i> <span className="nav-label">Minor view</span>
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </nav>

                    <div id="page-wrapper" className="gray-bg">
                        <div className="row border-bottom">
                            <nav className="navbar navbar-static-top white-bg" role="navigation"
                                 style={{marginBottom: 0}}>
                                <div className="navbar-header">
                                    <a className="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i
                                        className="fa fa-bars"/> </a>
                                    <form role="search" className="navbar-form-custom" method="post" action="#">
                                        <div className="form-group">
                                            <input type="text" placeholder="Search for something..."
                                                   className="form-control" name="top-search" id="top-search"/>
                                        </div>
                                    </form>
                                </div>
                                <ul className="nav navbar-top-links navbar-right">
                                    <li>
                                        <a href="#">
                                            <i className="fa fa-sign-out"></i> Log out
                                        </a>
                                    </li>
                                </ul>

                            </nav>
                        </div>
                        <div className="wrapper wrapper-content animated fadeInRight">
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="text-center m-t-lg">
                                        <h1>
                                            INSPINIA Static Seed Project for BS4
                                        </h1>
                                        <small>
                                            It is an application skeleton for a typical web app. You can use it to
                                            quickly bootstrap your webapp projects and dev environment for these
                                            projects.
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="footer">
                            <div className="pull-right">
                                10GB of <strong>250GB</strong> Free.
                            </div>
                            <div>
                                <strong>Copyright</strong> Example Company &copy; 2014-2018
                            </div>
                        </div>

                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}><Image src="/vercel.svg" alt="Vercel Logo" width={72}
                                                         height={16}/></span>
                </a>

                {/* Main Scripts */}
                <script src="js/jquery-3.1.1.min.js"></script>
                <script src="js/popper.min.js"></script>
                <script src="js/bootstrap.min.js"></script>
                <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
                <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

                {/* Plugins */}
                <script src="js/inspinia.js"></script>
                <script src="js/plugins/pace/pace.min.js"></script>

            </footer>
        </div>
    )
}
