import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Customers</title>
                <meta name="deScription" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <meta charSet="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <span dangerouslySetInnerHTML={{
                    __html: `<link href="css/bootstrap.min.css" rel="stylesheet"/>
                <link href="font-awesome/css/font-awesome.css" rel="stylesheet"/>
                <link href="css/animate.css" rel="stylesheet"/>
                <link href="css/style.css" rel="stylesheet"/>`
                }}>

                </span>
            </Head>

            <main className={styles.main}>
                <div id="wrapper">
                    <nav className="navbar-default navbar-static-side" role="navigation">
                        <div className="sidebar-collapse">
                            <ul className="nav metismenu" id="side-menu">
                                <li className="nav-header">
                                    <div className="dropdown profile-element">

                                        <span data-toggle="dropdown" className="dropdown-toggle">
                                            <span className="block m-t-xs font-bold">Example user</span>
                                            <span className="text-muted text-xs block">menu
                                                    <b className="caret"/>
                                                </span>
                                        </span>

                                        <ul className="dropdown-menu animated fadeInRight m-t-xs">
                                            <li>
                                                <Link href={'/'}>
                                                    <a className="dropdown-item">Logout</a>
                                                </Link>
                                            </li>
                                        </ul>
                                    </div>
                                    <div className="logo-element">
                                        IN+
                                    </div>
                                </li>
                                <li className="active">
                                    <Link href="/">
                                        <a>
                                            <i className="fa fa-th-large"/>
                                            <span className="nav-label">Customers</span>
                                        </a>
                                    </Link>
                                </li>
                                <li>
                                    <Link href="/">
                                        <a>
                                            <i className="fa fa-th-large"/>
                                            <span className="nav-label">Notifications</span>
                                        </a>
                                    </Link>
                                </li>
                            </ul>

                        </div>
                    </nav>

                    <div id="page-wrapper" className="gray-bg">
                        <div className="row border-bottom">
                            <nav className="navbar navbar-static-top  mb-0" role="navigation">
                                <div className="navbar-header">
                                    <a className="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#">
                                        <i className="fa fa-bars"/>
                                    </a>
                                    <form role="search" className="navbar-form-custom" action="search_results.html">
                                        <div className="form-group">
                                            <input type="text" placeholder="Search for something..."
                                                   className="form-control"
                                                   name="top-search" id="top-search"/>
                                        </div>
                                    </form>
                                </div>

                            </nav>
                        </div>
                        <div className="row wrapper border-bottom white-bg page-heading">
                            <div className="col-sm-4">
                                <h2>Project list</h2>
                                <ol className="breadcrumb">
                                    <li className="breadcrumb-item">
                                        <a href="index.html">Home</a>
                                    </li>
                                    <li className="breadcrumb-item active">
                                        <strong>Project list</strong>
                                    </li>
                                </ol>
                            </div>
                        </div>
                        <div className="wrapper wrapper-content animated fadeInUp">
                            <div className="row">
                                <div className="col-lg-12">

                                    <div className="ibox">
                                        <div className="ibox-title">
                                            <h5>All projects assigned to this account</h5>
                                            <div className="ibox-tools">
                                                <a href="" className="btn btn-primary btn-xs">Create new project</a>
                                            </div>
                                        </div>
                                        <div className="ibox-content">

                                            <div className="project-list">

                                                <table className="table table-hover">
                                                    <tbody>
                                                    <tr>
                                                        <td className="project-status">
                                                            <span className="label label-primary"/>
                                                        </td>
                                                        <td className="project-title">
                                                            <a href="project_detail.html">Dr. ABC</a>
                                                            <br/>
                                                            <small>Phone: 123 123 123 | Emergency: 123 123</small>
                                                        </td>
                                                        <td className="project-actions">
                                                            <a href="#" className="btn btn-white btn-sm">
                                                                <i className="fa fa-pencil"/> Edit
                                                            </a>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                {/* Main Scripts */}

                <Script strategy={'beforeInteractive'} src="../public/js/jquery-3.1.1.min.js"/>
                <Script strategy={'afterInteractive'} src="../public/js/popper.min.js"/>
                <Script strategy={'afterInteractive'} src="../public/js/bootstrap.min.js"/>
                <Script strategy={'afterInteractive'} src="../public/js/plugins/metisMenu/jquery.metisMenu.js"/>
                <Script strategy={'afterInteractive'} src="../public/js/plugins/slimscroll/jquery.slimscroll.min.js"/>

                {/* Plugins */}
                <Script src="../public/js/inspinia.js"></Script>
                <Script src="../public/js/plugins/pace/pace.min.js"></Script>

            </footer>
        </div>
)
}
