import Head from 'next/head'
import Link from 'next/link'
import {ChangeEvent, useState} from 'react'
import LoginAlert from '../components/login/LoginAlert'
import authService from '../services/authentication/authService'
import Image from 'next/image'
import styled from 'styled-components'

const SDivLoginPageWrapper = styled.div`
  .logo {
    transform: scale(2);
  }
`

export default function LoginPage() {

    /* Login logic */

    // 1. Get value of username input
    const [userName, setUserName] = useState<string>('')
    const handleUserNameInputChange = (event: ChangeEvent<HTMLInputElement>) => {
        setUserName(event.target.value)
    }

    // 2. Get value of password
    const [password, setPassword] = useState<string>('')
    const handlePasswordInputChange = (event: ChangeEvent<HTMLInputElement>) => {
        setPassword(event.target.value)
    }


    // 3. Click sign in > send data
    const handleClickSignIn = async () => {
        // Send data to server
        const data = await authService.login(userName, password)

        if (data && data?.status?.code === 200) {
            // Redirect if success
            if (data.data.role === 'admin') {
                location.assign('/doctors')
            } else {
                location.assign('/')
            }

        } else {
            // Show error if fail
            showLoginAlert()// Show an error message
        }
    }


    const [showLogin, setShowLogin] = useState(false)
    const showLoginAlert = () => {
        setShowLogin(true)

        setTimeout(() => {
            setShowLogin(false)
        }, 5000)
    }

    const handleKeyPress = (event: React.KeyboardEvent) => {
        if (event.key === 'Enter') {
            handleClickSignIn()
        }
    }

    /* Render */
    return (
        <SDivLoginPageWrapper className="gray-bg middle-box text-center loginscreen animated fadeInDown">
            <style dangerouslySetInnerHTML={{__html: `body{background: #f3f3f4}`}}/>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <meta charSet="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <link href="css/bootstrap.min.css" rel="stylesheet"/>
                <link href="font-awesome/css/font-awesome.css" rel="stylesheet"/>

                <link href="css/animate.css" rel="stylesheet"/>
                <link href="css/style.css" rel="stylesheet"/>
            </Head>

            <div>
                <div className="logo">
                    <Image width={500} height={250} src="/img/logo.png" alt="Phi Logo"/>
                </div>
                <h3>Welcome to PHI</h3>
                <p>Login in. To see it in action.</p>
                <div className="m-t">
                    <div className="form-group">
                        <input type="email" onChange={handleUserNameInputChange} value={userName}
                               className="form-control" placeholder="Email" onKeyPress={handleKeyPress}
                               required/>
                    </div>
                    <div className="form-group">
                        <input type="password" onChange={handlePasswordInputChange} value={password}
                               onKeyPress={handleKeyPress}
                               className="form-control" placeholder="Password" required/>
                    </div>
                    {showLogin ? <LoginAlert/> : null}
                    <button onClick={handleClickSignIn}
                            className="btn btn-primary block full-width m-b">Login
                    </button>
                    <Link href={`/forgot-password`}>
                        <a><small>Forgot password?</small></a>
                    </Link>
                    <p className="text-muted text-center">Do not have an account?</p>
                    <Link href={`/signup`}>
                        <a className="btn btn-sm btn-white btn-block">Create an account</a>
                    </Link>
                </div>
            </div>
        </SDivLoginPageWrapper>
    )
}