import Head from 'next/head'
import Link from 'next/link'

export default function LoginPage() {
    return (
        <div className="gray-bg middle-box text-center loginscreen animated fadeInDown">
            <style dangerouslySetInnerHTML={{__html: `body{background: #f3f3f4}`}}/>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <meta charSet="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <link href="css/bootstrap.min.css" rel="stylesheet"/>
                <link href="font-awesome/css/font-awesome.css" rel="stylesheet"/>

                <link href="css/animate.css" rel="stylesheet"/>
                <link href="css/style.css" rel="stylesheet"/>
            </Head>

            <div>
                <div>

                    <h1 className="logo-name">PHI</h1>

                </div>
                <h3>Welcome to PHI</h3>
                <p>Login in. To see it in action.</p>
                <form className="m-t" role="form" action="index.html">
                    <div className="form-group">
                        <input type="email" className="form-control" placeholder="Username" required/>
                    </div>
                    <div className="form-group">
                        <input type="password" className="form-control" placeholder="Password" required/>
                    </div>
                    <button type="submit" className="btn btn-primary block full-width m-b">Login</button>

                    {/*<a href="#"><small>Forgot password?</small></a>*/}
                    {/*<p className="text-muted text-center"><small>Do not have an account?</small></p>*/}
                    <Link href=""><a className="btn btn-sm btn-white btn-block">Create an account</a></Link>
                </form>
            </div>
        </div>
    )
}