import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../../styles/Home.module.css'
import LeftNavigation from "../../components/common/LeftNavigation";
import PageHeading from "../../components/common/PageHeading";
import PatientHeading from "../../components/patients/PatientHeading";
import Image from "next/image";
import PatientTabHeading from "../../components/patient-details/PatientTabHeading";
import HistoryPatient from "../../components/patient-details/HistoryPatient/HistoryPatient";
import Tab1 from "../../components/patient-details/HistoryPatient/Tab1";
import Doctor from "../../components/patient-details/DoctorPatient/Doctor";
import DoctorPatientEdit from "../../components/patient-details/DoctorPatient/DoctorPatientEdit";
import Tab2 from "../../components/patient-details/DoctorPatient/Tab2";
import Tab3 from "../../components/patient-details/AllergyPatient/Tab3";
import Tab4 from "../../components/patient-details/Events/Tab4";
import Tab5 from "../../components/patient-details/Prescription/Tab5";
import {useEffect, useState} from "react";
import {TPatientDataList} from "../../services/types";
import patientService from "../../services/patientService";

export default function PatientDetailsPage() {

    const [data, setData] = useState<TPatientDataList>([])
    useEffect(() => {
        // Get data
        (async () => {
            const data = await patientService.getPatientList()
            if (data.status === '200') {
                setData(data.data)
            }
        })()
    }, [])
    return (
        <div className={styles.container}>
            <Head>
                <title>Customers</title>
                <meta name="deScription" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>

                <meta charSet="utf-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

                <span dangerouslySetInnerHTML={{
                    __html: `<link href="/css/bootstrap.min.css" rel="stylesheet"/>
                <link href="/font-awesome/css/font-awesome.css" rel="stylesheet"/>
                <link href="/css/animate.css" rel="stylesheet"/>
                <link href="/css/style.css" rel="stylesheet"/>`
                }}>

                </span>
            </Head>

            <main className={styles.main}>
                <div id="wrapper">
                    <LeftNavigation/>
                    <div id="page-wrapper" className="gray-bg">
                        <PageHeading pageName={"Patient Details"}/>
                        <div className="wrapper wrapper-content animated fadeInUp">
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="ibox">
                                        <div className="ibox-content">
                                            <div className="row">
                                                <div className="col-lg-12 tab-seeContent">
                                                    <PatientHeading patientData1={}/>
                                                    <div className="row m-t-sm">
                                                        <div className="col-lg-12">
                                                            <div className="panel blank-panel">
                                                                <div className="panel-heading">
                                                                    <div className="panel-options">
                                                                        <PatientTabHeading/>
                                                                    </div>
                                                                </div>
                                                                <div className="panel-body">
                                                                    <div className="tab-content">
                                                                        <Tab1/>
                                                                        <Tab2/>
                                                                        <Tab3/>
                                                                        <Tab4/>
                                                                        <Tab5/>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                {/* Main Scripts */}

                <Script strategy={'beforeInteractive'} src="/js/jquery-3.1.1.min.js"/>
                <Script strategy={'afterInteractive'} src="/js/popper.min.js"/>
                <Script strategy={'afterInteractive'} src="/js/bootstrap.min.js"/>
                <Script strategy={'afterInteractive'} src="/js/plugins/metisMenu/jquery.metisMenu.js"/>
                <Script strategy={'afterInteractive'} src="/js/plugins/slimscroll/jquery.slimscroll.min.js"/>

                {/* Plugins */}
                <Script src="js/inspinia.js"></Script>
                <Script src="js/plugins/pace/pace.min.js"></Script>

            </footer>
        </div>
    )
}
